### ISSUE TITLE
Sample generations

### ISSUE THREAD

**Issue by nurmukhametov** [xerub/ropc#1]
Can you provide in README how-to for repeating chain generation for samples? Do ropc support only ARM/Mach-O executables?

**Comment by xerub** [comment]
A big update is imminent. It'll bring x86/x86_64, ELF support and a more sane example (with README). Stay tuned.

**Comment by xerub** [comment]
You may want to take a look at this:
https://github.com/xerub/ropc/blob/master/sample/README
